controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

blog_add:
    path: /blog/add
    controller: App\Controller\BlogController::add
    methods: [GET, POST]

blog_show:
    path: /blog/{id}
    controller: App\Controller\BlogController::show
    methods: [GET]

instagram_stats:
    path: /instagram/stats
    controller: App\Controller\InstagramStatsController::stats
    methods: [GET]
